name: Build and Upload Executable

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # Uruchamia raz w tygodniu w niedzielę o północy
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Wybierz odpowiednią wersję Pythona

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install resources
      run: |
        chmod +x installResources.sh
        ./installResources.sh

    - name: Install pyinstaller
      run: |
        python -m pip install pyinstaller
         - name: Install pyinstaller
      run: |
        python -m pip install pyyaml

    - name: Build executable
      run: |
        pyinstaller --onefile program.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: program-exe
        path: ./dist/program.exe
